config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boardgames
  root 'boardgames#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root 'admin#dashboard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     if user
      if user.kind == 'employee'
        can :dashboard, :all
        can :access, :rails_admin
        can :manage, Boardgame #,status: :active
        can :read, Category #,status: :active
        can :manage, Client
        can :read, Plan #,status: :active
        can :manage, Rent
        can :read, Situation #,status: :active
        can :manage, Subscription
      elsif user.kind == 'manager'
        can :manage, :all
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  # enum copy: [:copy_1, :copy_2, :copy_3, :copy_4, :copy_5]
  enum copy: ['cópia 1', 'cópia 2', 'cópia 3', 'cópia 4', 'cópia 5']
  belongs_to :category
  belongs_to :situation
  has_many :rents
  has_paper_trail
  
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :boardgames
  validates :days, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  enum status: [:active, :inactive]
  has_many :rents
  has_one :subscription
  validates :name, :document, :email, :phone, :address, :birthday, presence: true
  has_paper_trail
  
  
  mount_uploader :documentphoto, DocumentphotoUploader
  
  # before_create do
  #   write_attribute(:document, document.to_cpf_format)
  # end
  
  before_save do
    if !CpfUtils.valid_cpf?(document)
      throw :abort
    end
    write_attribute(:document, document.to_cpf_format)
  end
  
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/rent.rb
class Rent < ApplicationRecord
  enum status: [:rented, :returned, :overdue]
  belongs_to :client
  belongs_to :boardgame
  belongs_to :plan
  belongs_to :user
  has_paper_trail
  
  delegate :client, to: :boardgame, prefix: true
  validates :rent_date, presence: true

  
  # impede a criacao de um aluguel de jogos fixos/nao locaveis
  before_create do
    if !self.boardgame.category.rentable
      throw :abort
    end
    # not allow to rent a already rented boardgame
    if status == "rented"
      if self.boardgame.situation_id != 1
        throw :abort
      end
    end
  end
  
  
  # Put automatically the expected return date for each category
  before_create do
      write_attribute(:expected_return_date, rent_date + (self.boardgame.category.days).days)
  end
  
  after_save do
    if status == "rented"
      self.boardgame.update( situation_id: 2)
    elsif status == "returned"
      self.boardgame.update( situation_id: 1)
    elsif status == "overdue"
      self.boardgame.update( situation_id: 2)  
    end
  end
  
   # Virtual field method to show on boardgame admin view
  def rental_client
    if status == "rented"
      "#{self.client.name}, no prazo."
    elsif status == "overdue"
      "#{self.client.name}, atrasado!"
    end
  end
  
  # Virtual field method to show on client admin view
  def rented_games_client
    "#{self.boardgame.name}"
  end

  # Virtual field method
  def rental_boardgame
    [self.client, self.boardgame].compact.join(', ')
  end
  
  # run  $ rails runner "Rent.check_overdue"
  def self.check_overdue
    rent = Rent.where(status: 'rented').where("expected_return_date < ?", Date.today).all
    #1.day.ago does not work, because rails put time, and find no records, since this is only date, not datetime)
    rent.update(status: 'overdue')
  end

end

app/models/situation.rb
class Situation < ApplicationRecord
  has_many :boardgames
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  enum status: [:active, :inactive, :suspended, :overdue]
  belongs_to :client
  belongs_to :plan
  belongs_to :user
  has_paper_trail
  
  validates :subscription_date, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  enum kind: [:employee, :manager]
  enum status: [:active, :inactive]
  has_many :rents
  has_many :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
  def index
    # @boardgames = Boardgame.all.order("name ASC")
    
    # search form https://medium.com/@zylberberg.jonathan/creating-a-search-form-in-rails-5-77fdef6be74d
    if params[:boardgame]
      @boardgames = Boardgame.where('LOWER(name) ILIKE ?', "%#{params[:boardgame]}%")
      #for case insensitive, in Postgress and SQLite (ILIKE broke in SQLite)
      #https://stackoverflow.com/questions/6892034/postgres-case-insensitive-searching-with-rails
      # @boardgames = Boardgame.where("LOWER(name) LIKE LOWER('%#{params[:boardgame]}%')")
                                    
    else
      @boardgames = Boardgame.all.order("name ASC")
    end
    
  end
  
  def show
  end
  
  def boardgame_params
    params.require(:boardgame).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/boardgames/_navbar.html.erb
<nav class="navbar is-warning is-fixed-top">
  <div class="navbar-brand">
    
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-2 is-size-3-mobile has-text-centered">Acervo Ludoteca</h1>
    <% end %>
    
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  
  
  <%# search form %>
  <div class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field">
          <div class="control has-icons-left">
          <%= form_tag(boardgames_path, method: :get) do %>
            <%= text_field_tag :boardgame, params[:boardgame], placeholder: "Tente 'catan'", class: "input is-rounded" %>
              <span class="icon is-small is-left">
                  <i class="fa fa-search"></i>
              </span>
          </div>
          <div class="control">    
            <%= submit_tag 'Search', name: nil, style: "display:none;", class: "button is-dark" %>
          </div>
          <% end %>
        </div>
      </div>          
    </div>
  </div>
</nav>

app/views/boardgames/_navbar_search_mobile.html.erb
<nav class="navbar is-warning is-fixed-bottom is-hidden-tablet">
  <div class="navbar-brand">
    <div class="navbar-item">
      <div class="field has-addons">
        <div class="control has-icons-left">
          <%= form_tag(boardgames_path, method: :get) do %>
            <%= text_field_tag :boardgame, params[:boardgame], placeholder: "Tente 'catan'", class: "input is-rounded" %>
              <span class="icon is-small is-left">
                  <i class="fa fa-search"></i>
              </span>
        </div>
        <div class="control has-icons-right">    
            <%= submit_tag '', name: nil, class: "button is-info is-success is-rounded" %>
              <span class="icon is-small is-right">
                <i class="fa fa-search"></i>
              </span
        </div>
          <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/boardgames/index.html.erb
<%= render 'navbar' %>
<%= render 'navbar_search_mobile' %>
<br />
 <% if @boardgames.blank? %>
      <h4>Não há jogos com o nome '<%= params[:boardgame] %>' no acervo.</h4>
 <% end %>

<section class="section">  
  <div class="columns is-multiline is-centered">    
    <% @boardgames.group_by(&:name).each do |name, games| %>
      <div class="column is-5-tablet is-4-desktop is-3-widescreen">
        <div class="box">
          <div class="media">
            
            <div class="media-left">
              <figure class="image image is-128x128">
                <% games.each_with_index do |game, i| %>
                  <% if i == 0 %>
                    <% if game.image.present? %>
                      <%= cl_image_tag(game.image, :width => 128, :height => 128, :crop => :fill) %>
                    <% else %>
                      <%= image_tag 'logo-ludoteca-quadrada.png' %>
                    <% end %>
                  <% end %>
                <% end %>
              </figure>
            </div>
            
            
            <div class="media-content">
            
            <strong><%= name %></strong><br />
              <%# sort by copys https://stackoverflow.com/a/6783390/3650719 %>
              <% games.sort {|a,b| a.copy <=> b.copy}.each do |game| %>
                <div class="field is-grouped">
                  <div class="control">
                    <div class="tags has-addons">
                      <span class="tag" >
                        <%= game.copy %>
                      </span>
                      <% if !game.category.rentable? %>
                        <span class="tag is-info">
                          <%= "Fixa" %>
                        </span>
                      <% elsif game.situation.name == "Disponível" %>
                        <span  class="tag is-success">
                          <%= game.situation.name %>
                        </span >
                      <% else %>
                        <span  class="tag is-light">
                          <%= game.situation.name %>
                        </span >
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
    
    
    <% if @boardgames.blank? %>
      <h4>Não há jogos com o nome '<%= params[:boardgame] %>' no acervo.</h4>
    <% end %>
    
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acervo Ludoteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= render 'application/favicon' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>